### PR TITLE
Updated Textures

### PR DESCRIPTION
**Pull request by SilverDavidMC**
I updated the textures and logo per Jonathan's request.

Logo
New Textures

### CODE REVIEW

**Comment by Jonathing** [comment]
Ignore the restyled bot. I forgot to configure it and it's confused by some of the json models you uploaded.

**Review by Jonathing — APPROVED** [review]
Everything looks good. I'll rebase this in just a minute.

**Comment by theishiopian** [comment]
Oh, wow, actual art! Its about time my bodgey pixel art got replaced

**Comment by theishiopian** [comment]
I'm especially a huge fan of the paving stones and fascines.

**Pull request merged**
